---
title: "CKME 136 Project"
output: pdf_document
---

1. data preparation

#1.1 Import Data.
```{r}
rawdata <- data.frame(read.csv("C:/ckme136/default of credit card clients.csv",header = T,skip = 1, stringsAsFactors = T))
str(rawdata)
```


#1.2 Check duplicates and missing values.
```{r}
sum(duplicated(rawdata))
colSums(is.na(rawdata))
# No duplicates and no missing value
```

#1.3 Rename class attribute and Convert columns to factors according to the data description .
```{r}
colnames(rawdata)[25]<-"DEFAULT"
PAY_Name<-paste0("PAY_",c(0,2:6))
ToFactorCol<-c("SEX","EDUCATION","MARRIAGE",PAY_Name,"DEFAULT")
rawdata[ToFactorCol] <- lapply(rawdata[ToFactorCol], factor)
str(rawdata)

# categorical data and numeric data

catdata<-rawdata[ToFactorCol]
numdata<-rawdata[!names(rawdata)%in%c("ID",ToFactorCol)]
# outliers 
View(lapply(numdata,boxplot))
```

2 Descriptive analysis 

#2.2.Exploratory analysis of categorical data, Plot the distribution?
```{r}
lapply(catdata,table)
#distribution
lapply(ToFactorCol,function(x) plot(rawdata[x],ylim=c(0,30000),xlab=x,ylab="Frequency"))

# imbalanced dataset class attribute "DEFAULT": no:23364, yes:6636

```

#2.3. Exploratory analysis of numeric data
```{r}

install.packages("corrplot")

library("corrplot")
rawdata$DEFAULT<-as.integer(rawdata$DEFAULT)
num_class<-cbind(numdata,rawdata$DEFAULT)
colnames(num_class)<-c(colnames(numdata),"DEFAULT")
corrdata<-cor(num_class)
corrplot.mixed(corrdata,lower.col = "black", number.cex = .6,cl.cex=0.7,tl.cex=0.6)

```
