3.1 Partitioning Data
```{r}
traindata<-rawdata[-1]
library(caTools)
set.seed(11)
split=sample.split(traindata$DEFAULT,SplitRatio = 0.8)
trainset=subset(traindata,split==TRUE)
testset=subset(traindata,split==FALSE)
#Standardizing data

trainset[-24]=lapply(trainset[-24],function(x) if(is.numeric(x)){scale(x,center = T,scale = T)}else x)
testset[-24]=lapply(testset[-24],function(x) if(is.numeric(x)){scale(x,center=T,scale=T)}else x)
head(trainset)
str(trainset)

```
3.2 imbalanced data resampling

```{r}
library(ROSE)
#over sampling
over_samp<-ovun.sample(DEFAULT ~ ., data=trainset,method="over",N=37382,seed = 1)$data
table(over_samp$DEFAULT)

#under sampling
under_samp<-ovun.sample(DEFAULT ~ ., data=trainset,method="under",N=10618,seed = 1)$data
table(under_samp$DEFAULT)

#both over$under
both_samp<-ovun.sample(DEFAULT ~ ., data=trainset,method="both",N=24000,p=0.5,seed = 1)$data
table(both_samp$DEFAULT)

#ROSE sampling
rose_samp<-ROSE(DEFAULT ~ ., data=trainset,seed = 1)$data
table(rose_samp$DEFAULT)

```
3.3 Classification 
#3.3.1 Decision tree
```{r}
library(rpart)
tree.imb<-rpart(DEFAULT~.,data=trainset)
tree.rose<-rpart(DEFAULT ~., data=rose_samp)
tree.over<-rpart(DEFAULT ~., data=over_samp)
tree.under<-rpart(DEFAULT ~., data=under_samp)
tree.both<-rpart(DEFAULT ~., data=both_samp)

pred.tree.imb<-predict(tree.imb, newdata = testset[-24],type = "class")
pred.tree.rose <- predict(tree.rose, newdata = testset[-24],type = "class")
pred.tree.over <- predict(tree.over, newdata = testset[-24],type = "class")
pred.tree.under <- predict(tree.under, newdata = testset[-24],type = "class")
pred.tree.both <- predict(tree.both, newdata = testset[-24],type = "class")
library(lattice)
library(ggplot2)
library(caret)
library(e1071)
library(pROC)
confusionMatrix(pred.tree.both,testset$DEFAULT,mode = "prec_recall", positive="1")
confusionMatrix(pred.tree.imb,testset$DEFAULT,mode = "prec_recall", positive="1")
confusionMatrix(pred.tree.rose,testset$DEFAULT,mode = "prec_recall", positive="1")
confusionMatrix(pred.tree.over,testset$DEFAULT,mode = "prec_recall", positive="1")
confusionMatrix(pred.tree.under,testset$DEFAULT,mode = "prec_recall", positive="1")
```{r}
